#!/usr/bin/zsh

GIT_REPO=$HOME/raysite.git
TEMP_REPOSITORY=$HOME/raysite-deploy-temp
PUBLIC_WWW=/var/www/raysite

git clone --recursive $GIT_REPO $TEMP_REPOSITORY
chdir $TEMP_REPOSITORY
/home/raytray/.rvm/gems/ruby-2.2.1@global/wrappers/bundle install
/home/raytray/.rvm/gems/ruby-2.2.1@global/wrappers/bundle exec jekyll build -s $TEMP_REPOSITORY -d $PUBLIC_WWW
rm -Rf $TEMP_REPOSITORY
exit
